version: '3'
services:
  api-server:
    build: api-server
    command: /app/bin/api-server server config.yaml
    ports:
      - 8080:8080
    volumes:
      - ./api-server/build/install/api-server:/app
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      DEBUG: 1
      # LAMBDA_EXECUTOR: local
      LAMBDA_REMOTE_DOCKER: 0
      SERVICES: lambda,s3,stepfunctions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
