version: '3'
services:
  api-service:
    build: api-service
    ports:
      - 8080:8080
    # command: pipenv run flask run --host=0.0.0.0
    command: pipenv run uvicorn src.app:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api-service:/app
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      DEBUG: 1
      LAMBDA_DOCKER_FLAGS: -p 19891:19891
      LAMBDA_REMOTE_DOCKER: 0
      SERVICES: lambda,s3,stepfunctions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
